### PR TITLE
Feature-list-codecheckers

### PR DESCRIPTION
**Pull request by angelina-momin**
Solves issue [#71](https://github.com/codecheckers/register/issues/71)
Related codecheck repo [PR #90](https://github.com/codecheckers/register/pull/90) and [PR #97](https://github.com/codecheckers/register/pull/97)

The render_register function now creates a list of codecheckers as shown in the image below.
The codechecker name links to the codecheck website with all their codechecks.
The orcid ID links to their orcid pages.
The "JSON" links to the index.json file

Changes made:
- Bumped version to `0.4.0`
- Move all config settings from `register.R` to a new `inst/extdata/config.R` file.
- Created functions `render_table_codecheckers` for html and json files which are now called in render_register function
- Added new template file for non register tables like the codecheckers table
- Move all templates to `inst/extdata/templates` folder in this repo 
- Update the Rmarkdown files for the new functions

image

### CODE REVIEW

**Comment by angelina-momin** [comment]
@nuest just realized there is a discrepancy between the actual number of codechecks and the number of codechecks written on this page. This has to do with the fact that for some codechecks there is more than one author hence those codechecks are counted more than once. The total no. of codechecks as shown above is = sum of entries in the "no.of codechecks" column but the "no. of codechecks" column does not account for this double counting.

Should I change the subtitle to show total codechecks without double count and leave the no. of codechecks column as is? A bit confusing for a user if they add up the "no. of codechecks" and see the numbers dont match but the best solution I could think of. Possibly adding a small text stating that some codechecks have multiple authors?

**Comment by nuest** [comment]
Yes, change the number to checks without double count and please do add a short info about the reason for the discrepancy (though I don't think readers will take time to do the math ;-) ).

**Comment by angelina-momin** [comment]
@nuest let me know what you think of this. I'll also open this PR for review again and merge once you're good with it
image

**Review by nuest — APPROVED** [review]

**Comment by nuest** [comment]
LGTM!

Good to see he tests are back in line, too.

**Pull request merged**
